import ToggleTheme from "@/components/ToggleTheme";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import CountingProvider from "@/components/CountingProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <main className="flex flex-1 w-full max-w-3xl flex-col items-center justify-between py-32 px-16 sm:items-start">
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={true}
            disableTransitionOnChange
          >
            <ToggleTheme />
            <CountingProvider>{children}</CountingProvider>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
